### ISSUE TITLE
Rendu TP3

### ISSUE THREAD

**Issue by Julienbtn** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-1-bertrand_bontron#1]

**Comment by Slashgear** [comment]
⚠️ Pour les verify, vous n'etes pas obligé de faire un after

⚠️ Le rapport il n'y a pas beaucoup d'effort pas d'uml pas d'appercu de la couverture de test.


```java
public static Collection<IPerson> filterByAgeInterval(Collection<IPerson> persons, GregorianCalendar date, int ageMin, int ageMax)
    {
        if (ageMin > ageMax || ageMin < 0)
            throw new IllegalArgumentException("ageMin ne peut pas �tre inf�rieur � 0 ou sup�rieur � ageMax");
        
        ArrayList<IPerson> res = new ArrayList<>();
        persons.forEach(n -> {
            if (n.getAge(date) >= ageMin && n.getAge(date) <= ageMax)
                res.add(n);
            });
        
        return res;
    }
```
Pas très optimisé tout ça ⚠️ 

Les `atLeast`et `atMost` c'est un aveu que vous ne vérifiez pas le nombre d'appels que vous faites à vos méthodes mockées.

**Comment by podoko** [comment]
- j'ai déplacé les verify dans le test le plus adéquat (je voulais vérifier que toutes les fonctions étaient anonymes sans faire de copier/coller)
- Julien a rajouté du contenu
- J'ai viré le double appel à `getAge`
- Je comprends pas bien le problème avec `atLeast` et `atMost`. Le `atLeast` prend au pied de la lettre le "en utilisant au moins une fois la méthode getAge", on peut utiliser `atLeastOnce` qui aurait le même effet ou en simple `verify` équivalant à un `times(1)` (modifié comme tel) si on veut s'assurer que la fonction n'est appelée qu'une fois ; `atMost` peut être remplacée par `never` (modifié comme tel) ou `verifyNoMoreInteractions` mais je trouve ce dernier trop restrictif (si `getAge` faisait appel à une fonction `getDateNaissance` par exemple). Si c'est pas le problème, j'ai pas bien compris le problème

**Comment by Slashgear** [comment]
Ce qui me gène avec les atLeast => si quelqu'un vient ajouter un appel à une méthode de service et que cet appel fait doublon. Ton test va pas le faire remarquer.
La par exemple, tu dois te dire qu'au maximum tu dois appeler getAge qu'une fois par personne.

**Comment by Slashgear** [comment]
👍
